#!/bin/bash
#
# Check if the SDC repos (those listed in targets.json) are prepared (branched
# or tagged as appropriate) for an SDC release build. Will also apply
# missing branch/tag with the '-a' flag.
#

#set -x
set -o errexit


#---- globals, config

TOP=$(cd $(dirname $0)/../; pwd)
WORKDIR="/var/tmp/check-repos-for-release.$$"


#---- functions

function cleanup() {
    rm -rf $WORKDIR
}

function usage() {
    if [[ -n "$1" ]]; then
        echo "error: $1"
        echo ""
    fi
    echo "Usage:"
    echo "  check-repos-for-release [OPTIONS] RELEASE-DATE"
    echo ""
    echo "Options:"
    echo "  -c CREDS        Provide creds for mo.joyent.com. If not given"
    echo "                  will use 'MOLYBDENUM_CREDENTIALS' envvar."
    echo "  -a              *Apply* missing branch and/or tag (as appropriate)"
    echo "                  The 'illumos-extra' repo is just tagged, all"
    echo "                  others are just branched."
    echo "  -r REPO         Just run for the given repository. If not given"
    echo "                  then all repos in 'targets.json' are used. Can be"
    echo "                  specified multiple times."
    echo ""
    echo "Examples:"
    echo "  check-repos-for-release 20111020"
    echo "  check-repos-for-release -r usb-headnode 20111020"
    echo "  check-repos-for-release -a 20111020"
    exit 1
}

function fatal {
    echo "$(basename $0): error: $1"
    exit 1
}

function get_repo_url_from_targ {
  local targ=$1
  local urls=$(cat targets.json | ./tools/json $targ | grep -v undefined | ./tools/json repos | ./tools/json -a url )
  local ret=""
  for url in $urls; do
   ret="$ret $(echo $url)" # | cut -d ':' -f2 | xargs -I {} basename {} .git)"
  done
  echo $ret
}

function get_repo_name_from_url {
  targ=$1
  echo $targ | cut -d ':' -f2 | xargs -I {} basename {} .git
}

function apply_missing {
    local repo_targ=$1
    local tag=$2
    local branch=$3
    local repo_urls="$(get_repo_url_from_targ $repo_targ)"
    #local repo_name=$(get_repo_name_from_targ $repo_targ)

    echo "Prep $repo ($repo_url) for release: branch '$branch', tag '$tag'."
    mkdir -p $WORKDIR
    for repo_url in $repo_urls; do
      repo_name=$(get_repo_name_from_url $repo_url)
      cd $WORKDIR;
      git clone $repo_url $repo_name;
      cd $repo_name;
      git checkout master;
      if [[ ! -z "$tag" ]]; then
        # Consider '-B' to force reset of branch if already exists.
        git tag -a "$tag" -m "$tag release"
        git push -q --tags
      fi
      if [[ ! -z "$branch" ]]; then
        # Consider '-B' to force reset of branch if already exists.
        git checkout -b $branch
        git push -q origin $branch
      fi
    done
    cd $TOP
}


#---- mainline

trap cleanup EXIT

APPLY=0   # whether to apply a branch/tag to repo
CREDS=
REPOS=
while getopts "hac:r:" c; do
    case "$c" in
    h)
        usage
        ;;
    a)
        APPLY=1
        ;;
    c)
        CREDS=$OPTARG
        ;;
    r)
        REPOS="$REPOS $OPTARG"
        ;;
    *)
        usage "illegal option -- $OPTARG"
        ;;
    esac
done
shift $((OPTIND - 1))


RELEASE=$1
if [[ -z "$RELEASE" ]]; then
    usage "no RELEASE given"
fi
is_date=$(echo $RELEASE | grep '^[0-9]\{8\}$' || true)
if [[ -z "$is_date" ]]; then
    usage "given RELEASE, '$RELEASE', is not an 8-digit date"
fi
BRANCH=release-$RELEASE
TAG=$RELEASE

if [[ -z "$CREDS" ]]; then
    CREDS=$MOLYBDENUM_CREDENTIALS
fi
if [[ -z "$CREDS" ]]; then
    usage "no mo.joyent.com crendentials: use '-c CREDS' or set MOLYBDENUM_CREDENTIALS"
fi


if [[ -z "$REPOS" ]]; then
  TARGETS=$(node -e "var fs = require('fs');
      var targets = JSON.parse(fs.readFileSync('targets.json'));
      Object.keys(targets).forEach( function(targ) { console.log(targ) });" | xargs)
fi

for target in $TARGETS; do
  if [[ $target == 'all' ]]; then
    continue
  fi
  repos=$(cat targets.json | ./tools/json ${target}.repos  | ./tools/json -a url | cut -f 2 -d ':' | xargs -I {} basename {} .git)
  repos+=" git@git.joyent.com:mountain-gorilla.git"
  for repo in $repos; do
    hit=$(curl -sS https://mo.joyent.com/api/repos/$repo/refs -u $CREDS | $TOP/tools/json branches | grep "\"$BRANCH\"" || true)
    if [[ -z "$hit" ]]; then
      if [[ $APPLY -eq 1 ]]; then
        echo "$repo: missing '$BRANCH' branch"
        apply_missing $target "$TAG" "$BRANCH"
      else
        echo "$repo: FAIL (no '$BRANCH' branch, use -a to apply)"
      fi
    else
      echo "$repo: OK"
    fi
  done
done
