#!/bin/bash
#
# Check if the SDC repos (those listed in targets.json) are prepared (branched
# or tagged as appropriate) for an SDC release build. Will also apply
# missing branch/tag with the '-a' flag.
#

#set -x
set -o errexit


#---- globals, config

TOP=$(cd $(dirname $0)/../; pwd)
WORKDIR="/var/tmp/check-repos-for-release.$$"


#---- functions

function cleanup() {
    rm -rf $WORKDIR
}

function usage() {
    if [[ -n "$1" ]]; then
        echo "error: $1"
        echo ""
    fi
    echo "Usage:"
    echo "  check-repos-for-release [OPTIONS] RELEASE-DATE"
    echo ""
    echo "Options:"
    echo "  -c CREDS        Provide creds for mo.joyent.com. If not given"
    echo "                  will use 'MOLYBDENUM_CREDENTIALS' envvar."
    echo "  -a              *Apply* missing branch and/or tag (as appropriate)"
    echo "                  The 'illumos-extra' repo is just tagged, all"
    echo "                  others are just branched."
    echo "  -t TARGET       Just run for the given MG target. If not given"
    echo "                  then all targets in 'targets.json' are used. Can be"
    echo "                  specified multiple times."
    echo ""
    echo "Examples:"
    echo "  check-repos-for-release 20111020"
    echo "  check-repos-for-release -t usbheadnode 20111020"
    echo "  check-repos-for-release -a 20111020"
    exit 1
}

function fatal {
    echo "$(basename $0): error: $1"
    exit 1
}

function get_repo_url_from_targ {
  local targ=$1
  local urls=$(cat ${TOP}/targets.json | ${TOP}/tools/json $targ | grep -v undefined | ${TOP}/tools/json repos | ${TOP}/tools/json -a url )
  local ret=""
  for url in $urls; do
   ret="$ret $(echo $url)" # | cut -d ':' -f2 | xargs -I {} basename {} .git)"
  done
  echo $ret
}

function get_repo_name_from_url {
  targ=$1
  echo $targ | cut -d ':' -f2 | xargs -I {} basename {} .git
}

function apply_missing_to_repo {
    local repo_url=$1
    local tag=$2
    local branch=$3

    echo "Prep repo $repo_url for release: branch '$branch', tag '$tag'."
    mkdir -p $WORKDIR
    repo_name=$(get_repo_name_from_url $repo_url)
    cd $WORKDIR;
    git clone $repo_url $repo_name;
    cd $repo_name;
    git checkout master;
    if [[ ! -z "$tag" ]]; then
      # Consider '-B' to force reset of branch if already exists.
      git tag -a "$tag" -m "$tag release"
      git push -q --tags
    fi
    if [[ ! -z "$branch" ]]; then
      # Consider '-B' to force reset of branch if already exists.
      git checkout -b $branch
      git push -q origin $branch
    fi
}

function check_repo_url {
    local repo_url=$1
    local targ=$2   # optional

    repo_name=$(get_repo_name_from_url $repo_url)
    local hit=$(curl -sS https://mo.joyent.com/api/repos/$repo_name/refs -u $CREDS \
        | $TOP/tools/json branches \
        | grep "\"$BRANCH\"" \
        || true)
    if [[ -z "$hit" ]]; then
      if [[ $APPLY -eq 1 ]]; then
        echo "Repo $repo_url ('$targ' target): missing '$BRANCH' branch"
        apply_missing_to_repo $repo_url "$TAG" "$BRANCH"
      else
        echo "Repo $repo_url ('$targ' target): FAIL (no '$BRANCH' branch, use -a to apply)"
      fi
    else
      echo "Repo $repo_url ('$targ' target): OK"
    fi
}

function check_targ {
    local targ=$1
    local repo_urls="$(get_repo_url_from_targ $targ)"
    for repo_url in $repo_urls; do
        check_repo_url $repo_url $targ
    done
}


#---- mainline

trap cleanup EXIT

APPLY=0   # whether to apply a branch/tag to repo
CREDS=
TARGETS=
while getopts "hac:t:" c; do
    case "$c" in
    h)
        usage
        ;;
    a)
        APPLY=1
        ;;
    c)
        CREDS=$OPTARG
        ;;
    t)
        TARGETS="$TARGETS $OPTARG"
        ;;
    *)
        usage "illegal option -- $OPTARG"
        ;;
    esac
done
shift $((OPTIND - 1))


RELEASE=$1
if [[ -z "$RELEASE" ]]; then
    usage "no RELEASE given"
fi
is_date=$(echo $RELEASE | grep '^[0-9]\{8\}$' || true)
if [[ -z "$is_date" ]]; then
    usage "given RELEASE, '$RELEASE', is not an 8-digit date"
fi
BRANCH=release-$RELEASE
TAG=$RELEASE

if [[ -z "$CREDS" ]]; then
    CREDS=$MOLYBDENUM_CREDENTIALS
fi
if [[ -z "$CREDS" ]]; then
    usage "no mo.joyent.com crendentials: use '-c CREDS' or set MOLYBDENUM_CREDENTIALS"
fi


if [[ -z "$TARGETS" ]]; then
    TARGETS=$(node -e "var fs = require('fs');
        var targets = JSON.parse(fs.readFileSync('targets.json'));
        Object.keys(targets).forEach( function(targ) { console.log(targ) });" | xargs)
fi

for targ in $TARGETS; do
  if [[ $targ == 'all' ]]; then
    continue
  fi
  check_targ $targ
done
check_repo_url git@git.joyent.com:mountain-gorilla.git '(none)'

