#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2018, Joyent, Inc.
#

#
# This script lives at <mountain-gorilla.git/tools/jenkins-build>. It is
# meant to be used for building SDC components in jenkins jobs. Like this:
#
#        set -o errexit
#        set -o pipefail
#
#        # Poorman's backup of last build run.
#        rm -rf MG.last
#        mkdir -p MG && mv MG MG.last
#        rm -rf MG
#
#        git clone git@github.com:joyent/mountain-gorilla.git MG
#        cp MG/tools/jenkins-build ./
#        ./jenkins-build
#
# E.g. https://jenkins.joyent.us/job/imgapi/configure
#

set -o errexit
unset LD_LIBRARY_PATH   # ensure don't get Java's libs (see OS-703)


#---- globals, config

# The Manta directory that build artifacts are uploaded to.  The same
# name is used for both public (under ~~/public) and private (under
# ~~/stor) artifacts.
MG_JENKINS_BUILDS_DIR=${MG_JENKINS_BUILDS_DIR:-builds}

#
# Refuse to build if /tmp is tmpfs until OS-5608 is fixed.
# Try to umount if mounted, if that fails: blow up.
#
if mount | grep ^/tmp; then
    if ! umount /tmp; then
        echo "FATAL: refusing to use mounted /tmp (See: RELENG-711)" >&2
        exit 1
    fi
fi

# ---- First pass:
# 1. parse params
# 2. change MG branch (if necessary) and restart
if [[ -z "$MG_JENKINS_BUILD_SECOND_PASS" ]]; then
    echo ""
    echo "#---------------------- start first pass"

    # Note: As of TOOLS-659, use of 'payload' in hooks is deprecated.
    #
    # If "payload" is defined, we presume this is from a post-receive hook.
    # `payload.ref` will defined the git branch. For "release-YYYYMMDD" branches
    # (the Joyent engineering convention for release branches) we'll be strict
    # and have:
    #   TRY_BRANCH=  BRANCH=$branch
    # but for other branches we'll be "nice" and use
    #   TRY_BRANCH=$branch  BRANCH=master
    # which allows, for example, a commit to a feature branch (say "foo") to
    # work when ancillary repos (like mountain-gorilla.git and usb-headnode.git)
    # don't have that branch.
    if [[ -n "$payload" ]]; then
        ref=$(echo "$payload" | json ref)
        if [[ $(echo "$ref" | cut -d/ -f2) != "heads" ]]; then
            echo "error: unexpected ref '$ref': is not 'refs/heads'"
            exit 1
        fi
        BRANCH=$(echo "$ref" | cut -d/ -f3)
        if [[ -z "$(echo $BRANCH | egrep '^release-[0-9]+' || true)" ]]; then
            TRY_BRANCH=$BRANCH
            BRANCH=master
        fi
    fi
    if [[ -z "$BRANCH" ]]; then
        BRANCH=master
    fi
    export BRANCH TRY_BRANCH
    echo "BRANCH: $BRANCH"
    echo "TRY_BRANCH: $TRY_BRANCH"

    cd MG
    if [[ -n "$TRY_BRANCH" ]]; then
        mg_has_try_branch=$(git branch -a | cut -c3- \
            | awk '{print $1}' | xargs -n1 basename \
            | (grep "^$TRY_BRANCH\$" || true))
        if [[ -n "$mg_has_try_branch" ]]; then
            git checkout $TRY_BRANCH
        else
            git checkout $BRANCH
        fi
    else
        git checkout $BRANCH
    fi

    # Restart jenkins-build now on the correct MG branch.
    export MG_JENKINS_BUILD_SECOND_PASS=1
    exec ./tools/jenkins-build
fi


# ---- Second pass: Do the build.

echo ""
echo "#---------------------- start second pass"

start_time=$(date +%s)
last_time=${start_time}

LOG=build.log
touch $LOG
exec > >(tee ${LOG}) 2>&1


echo ""
echo "#---------------------- env"

echo "MG repo commit sha: $(git describe --all --long --dirty | awk -F'-g' '{print $NF}')"
date
pwd
whoami
env



echo ""
echo "#---------------------- configure"

#
# The target defaults to the job name (e.g. platform-debug), but a job can also
# directly specify MG_TARGET as a parameter to over-ride this.
#
[[ -z "$MG_TARGET" ]] && MG_TARGET=$JOB_NAME

[[ -z "$BRANCH" ]] && BRANCH=master
# Note the "-c" to use a cache dir one up, i.e. shared between builds of this job.
CACHE_DIR=$(cd ../; pwd)/cache
if [[ "$CLEAN_CACHE" == "true" ]]; then
    rm -rf $CACHE_DIR
fi

# Builds that are joyent-specific get uploaded to a directory under
# /stor whereas all other builds now go under /public.  The specific
# directory is controlled by MG_JENKINS_BUILDS_DIR which defaults to
# "builds". In either case, dependencies come from the public directory.
if [[ ! -f targets.json ]]; then
    bash < targets.json.in | json > targets.json
fi
IS_PUBLIC=$(json < targets.json ${MG_TARGET}.public)
if [[ ${IS_PUBLIC} == "true" ]]; then
    JENKINS_OUTPUT_BASE="/public/${MG_JENKINS_BUILDS_DIR}"
else
    JENKINS_OUTPUT_BASE="/stor/${MG_JENKINS_BUILDS_DIR}"
fi

EXTRA_ARGS=""

if [[ ! -z ${USE_PREV_RELEASES_FOR} ]]; then
    EXTRA_ARGS="${EXTRA_ARGS}-R ${USE_PREV_RELEASES_FOR}"
fi

if [[ -z ${JOYENT_BUILD} || ${JOYENT_BUILD} == "true" ]]; then
    TRACE=1 ./configure -j -t $MG_TARGET -c "$CACHE_DIR" -b "$BRANCH" \
        -J /stor/builds -D /public/builds -O ${JENKINS_OUTPUT_BASE} \
        -B "$TRY_BRANCH" ${EXTRA_ARGS}
else
    TRACE=1 ./configure -t $MG_TARGET -c "$CACHE_DIR" -b "$BRANCH" \
        -D /public/builds -O ${JENKINS_OUTPUT_BASE} -B "$TRY_BRANCH" \
        ${EXTRA_ARGS}
fi

now_time=$(date +%s)
elapsed=$((${now_time} - ${last_time}))
last_time=${now_time}
echo "TIME: MG configure took ${elapsed} seconds"



echo ""
echo "#---------------------- make"

V=1 gmake $MG_TARGET

now_time=$(date +%s)
elapsed=$((${now_time} - ${last_time}))
last_time=${now_time}
echo "TIME: build took ${elapsed} seconds"



echo ""
echo "#---------------------- upload"

cp $LOG bits/$MG_TARGET/
gmake manta_upload_jenkins

if [[ ${MG_TARGET} == "smartos" ]] && [[ ${BRANCH} == release* ]]; then
    gmake smartos-release
fi

gmake jenkins_publish_image

now_time=$(date +%s)
elapsed=$((${now_time} - ${last_time}))
last_time=${now_time}
echo "TIME: upload took ${elapsed} seconds"
