#! /bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2017, Joyent, Inc.
#

#
# This script allows starting Jenkins builds from the command-line. To
# use this, you will need to get an API token for a Jenkins user, and
# provide it to the script through the JENKINS_AUTH environment variable
# or the -u option, in the form <user>:<api token>.
#

if [[ -n "$TRACE" ]]; then
	export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
	set -o xtrace
fi
set -o errexit
set -o pipefail

PROGNAME=$0

function usage() {
	if [[ -n $1 ]]; then
		printf "%s: %s\n" "$PROGNAME" "$1" >&2
	fi
	printf "usage:\n    $PROGNAME [-v] [-H url] [-b BRANCH] [-t TRY_BRANCH] [-u auth] project\n" >&2
	exit 2
}

while getopts ':H:u:b:t:hv' opt; do
	case $opt in
	H) JENKINS_URL=$OPTARG;;
	u) JENKINS_AUTH=$OPTARG;;
	b) BRANCH=$OPTARG;;
	t) TRY_BRANCH=$OPTARG;;
	v) VERBOSE=true;;
	h) usage;;
	:) usage "-$OPTARG requires an argument";;
	\?) usage "illegal option: -$OPTARG";;
	esac
done

PROJECT=${@:$OPTIND:1}

if [[ -z $PROJECT ]]; then
	usage "project to build must be specified"
fi

if [[ -z $JENKINS_URL ]]; then
	JENKINS_URL=https://jenkins.joyent.us
fi

if [[ -z $JENKINS_AUTH ]]; then
	usage "JENKINS_AUTH must be set to <user>:<api token> (get it here: ${JENKINS_URL}/me/configure)"
fi

if [[ -n $BRANCH && -n $TRY_BRANCH ]]; then
	usage "-b and -t cannot be used together"
fi

if [[ -n $BRANCH ]]; then
	printf "Building %s with BRANCH=%s\n" "$PROJECT" "$BRANCH"
	BUILD_PARAM=`printf '{"name":"BRANCH", "value": "%s"}' $BRANCH`
elif [[ -n $TRY_BRANCH ]]; then
	printf "Building %s with TRY_BRANCH=%s\n" "$PROJECT" "$TRY_BRANCH"
	BUILD_PARAM=`printf '{"name":"TRY_BRANCH", "value": "%s"}' $TRY_BRANCH`
fi

if [[ -n $VERBOSE ]]; then
	CURL_OPTS=(-i)
else
	CURL_OPTS=(-s)
fi

CRUMB_URL="$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"
BUILD_URL="$JENKINS_URL/job/$PROJECT/build"

# Fetch the CSRF token to send in our request's headers
CRUMB=`curl ${CURL_OPTS[@]} --user "$JENKINS_AUTH" "$CRUMB_URL"`

curl ${CURL_OPTS[@]} -X POST -H "$CRUMB" "$BUILD_URL" --user "$JENKINS_AUTH" \
    --data-urlencode json="{\"parameter\":[$BUILD_PARAM]}"
