#!/bin/bash
# Upload the bits dir to Manta
if [ "$TRACE" != "" ]; then
    export PS4='${BASH_SOURCE}:${LINENO}: '
    set -o xtrace
fi
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
BITS_DIR=bits/
PATH=$PATH:${TOP}/node_modules/manta/bin

# disable uploads on bh1 before doing anything else
if echo $NODE_LABELS | grep "bh1" 2>&1 >/dev/null ; then
    if [[ ${JOB_NAME} != "papi" ]]; then
        echo "Manta uploads have been disabled on this host"
        exit 0
    fi
fi

# --- Manta config
if [[ -z "$MANTA_KEY_ID" ]]; then
    export MANTA_KEY_ID=`ssh-keygen -l -f ~/.ssh/id_rsa.pub | awk '{print $2}' | tr -d '\n'`
fi
export MANTA_URL=https://us-east.manta.joyent.com
if [[ -z "$MANTA_USER" ]]; then
    export MANTA_USER="Joyent_Dev";
fi


function fatal {
    echo "$(basename $0): error: $1"
    exit 1
}

function errexit {
    [[ $1 -ne 0 ]] || exit 0
    fatal "error exit status $1 at line $2"
}

function print_help() {
    echo "Usage:"
    echo "  ./tools/mantaput-bits BRANCH TRY-BRANCH TIMESTAMP UPLOAD-BASE-DIR [SUBDIRS...]"
    echo ""
    echo "Upload bits to Manta. The UPLOAD-BASE-DIR is presumed to be a subdir of"
    echo "/stor/\${MANTA_USER}"
}

trap 'errexit $? $LINENO' EXIT

BRANCH=$1
shift
TRY_BRANCH=$1
shift
TIMESTAMP=$1
shift
UPLOAD_BASE_DIR=$1
shift
SUBDIRS=$*

UPLOAD_BRANCH=$TRY_BRANCH
if [[ -z "$UPLOAD_BRANCH" ]]; then
    UPLOAD_BRANCH=$BRANCH
fi

upload_subdir=$UPLOAD_BRANCH-$TIMESTAMP

start_time=$(date +%s)
echo "Uploading bits to /${MANTA_USER}/stor/${UPLOAD_BASE_DIR}/${upload_subdir}"

# need to create the directory structure first
if [[ -z "$SUBDIRS" ]]; then
    subs=$(find $BITS_DIR -type d)
    files=$(find $BITS_DIR -type f)
else
    for subdir in $SUBDIRS; do
        if [[ -d $BITS_DIR/$subdir ]]; then
          subs="$subs $(find $BITS_DIR/$subdir -type d)"
          files="$files $(find $BITS_DIR/$subdir -type f)"
        fi
    done
fi

for sub in $subs; do
    mmkdir -p /${MANTA_USER}/stor/${UPLOAD_BASE_DIR}/${upload_subdir}/${sub#${BITS_DIR}}
done

md5sums=""
# now we can upload the files
for file in $files; do
    mput -f $file /${MANTA_USER}/stor/${UPLOAD_BASE_DIR}/${upload_subdir}/${file#$BITS_DIR}
    md5sums="${md5sums}$(md5sum $file)\n"
done

# upload the md5sums and config.mk
echo -e $md5sums | mput -H 'content-type: text/plain' /${MANTA_USER}/stor/${UPLOAD_BASE_DIR}/${upload_subdir}/md5sums.txt
mput -f $BITS_DIR/config.mk /${MANTA_USER}/stor/${UPLOAD_BASE_DIR}/${upload_subdir}/config.mk 
# now update the latest link

echo "/${MANTA_USER}/stor/${UPLOAD_BASE_DIR}/${upload_subdir}" | mput -H 'content-type: text/plain' /${MANTA_USER}/stor/${UPLOAD_BASE_DIR}/${UPLOAD_BRANCH}-latest

echo "Uploaded to /${MANTA_USER}/stor/${UPLOAD_BASE_DIR}/${upload_subdir}"

end_time=$(date +%s)
elapsed=$((${end_time} - ${start_time}))
echo "Upload took ${elapsed} seconds (Manta path=/${MANTA_USER}/stor/${UPLOAD_BASE_DIR}/$upload_subdir)."
