#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

echo "<html>"
echo "<head><title>SmartOS ${1}</title></head>"
echo "<body>"
for x in `ls * | grep -v index.html`; do
  echo "<a href=\"$x\">$x</a><br>"
done
echo "<a href=\"md5sums.txt\">md5sums.txt</a>"
echo "</body></html>"
