#!/bin/bash
# vi: expandtab sw=4 ts=4
#
# Upload (possibly parts of) the bits dir.
#

if [ "$TRACE" != "" ]; then
    export PS4='${BASH_SOURCE}:${LINENO}: '
    set -o xtrace
fi
set -o errexit



#---- config, globals

TOP=$(cd $(dirname $0)/../; pwd)
BITS_DIR=bits

SSH_OPTIONS="-q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
SCP="scp $SSH_OPTIONS" 
SSH="ssh $SSH_OPTIONS" 



#---- internal support functions

function fatal {
    echo "$(basename $0): error: $1"
    exit 1
}


function errexit {
    [[ $1 -ne 0 ]] || exit 0
    fatal "error exit status $1 at line $2"
}


function print_help() {
    echo "Usage:"
    echo "  ./tools/upload-bits BRANCH TRY-BRANCH TIMESTAMP UPLOAD-BASE-DIR"
    echo ""
    echo "Upload bits. The UPLOAD-BASE-DIR is presumed to be a remote dir "
    echo "(i.e. user@host:path). 'TRY-BRANCH' is often empty. An MG build"
    echo "can be configured with '-B TRY-BRANCH' to use a feature branch"
    echo "for those constituent repos that have that branch. If there is"
    echo "'TRY-BRANCH', this will be used as the upload dir in favour of"
    echo "'BRANCH'."
    echo ""
    echo "Options:"
    echo "  -h           Print this help and exit."
    echo ""
    echo "Examples:"
    echo "  ./tool/upload-bits release-20110922 \"\" 20110927T143319Z stuff@stuff.joyent.us:builds/nightly"
    exit 0
}




#---- mainline

trap 'errexit $? $LINENO' EXIT

while getopts "hrf:" opt; do
    case $opt in
        h) print_help ;;
        ?) fatal "unknown option: $opt" ;;
    esac
    shift $((OPTIND-1))
done

BRANCH=$1
TRY_BRANCH=$2
TIMESTAMP=$3
UPLOAD_BASE_DIR=$4

UPLOAD_SERVER=$(echo "$UPLOAD_BASE_DIR" | awk -F: '{print $1}')
UPLOAD_BASE_LOCALDIR=$(echo "$UPLOAD_BASE_DIR" | awk -F: '{print $2}')
UPLOAD_BRANCH=$TRY_BRANCH
if [[ -z "$UPLOAD_BRANCH" ]]; then
    UPLOAD_BRANCH=$BRANCH
fi

# Determine the upload dir. If there is already a "$UPLOAD_BRANCH-$TIMESTAMP"
# dir, then we append a "-N" serial number.
existing_upload_dirs=$($SSH $UPLOAD_SERVER ls -d $UPLOAD_BASE_LOCALDIR/$UPLOAD_BRANCH-$TIMESTAMP* $UPLOAD_BASE_LOCALDIR/.$UPLOAD_BRANCH-$TIMESTAMP* 2>/dev/null || true)
last_upload_dir=$(echo $existing_upload_dirs | tail -1)
if [[ -z "$last_upload_dir" ]]; then
    upload_subdir=$UPLOAD_BRANCH-$TIMESTAMP
else
    serial=$(echo $last_upload_dir | awk -F- '{print $NF}')
    if [[ "${serial:(-1)}" == "Z" ]]; then
        next_serial=2
    else
        next_serial=$(( $serial + 1 ))
    fi
    upload_subdir=$UPLOAD_BRANCH-$TIMESTAMP-$next_serial
fi

# Upload to '.'-prefixed dir to hide it until fully uploaded.
echo "Uploading bits to <$UPLOAD_SERVER:$UPLOAD_BASE_LOCALDIR/$upload_subdir/>."
(cd ${BITS_DIR}/ && md5sum $(find ./ -type f) > md5sums.txt)
rsync -e "$SSH" -av $BITS_DIR/ $UPLOAD_SERVER:$UPLOAD_BASE_LOCALDIR/.$upload_subdir/

# Unhide and add a "$UPLOAD_BRANCH-$latest" symlink.
$SSH $UPLOAD_SERVER mv $UPLOAD_BASE_LOCALDIR/.$upload_subdir/ $UPLOAD_BASE_LOCALDIR/$upload_subdir/
$SSH $UPLOAD_SERVER "(cd $UPLOAD_BASE_LOCALDIR && rm -f $UPLOAD_BRANCH-latest && ln -s $upload_subdir $UPLOAD_BRANCH-latest)"

# Special note for stuff.joyent.us.
if [[ "$UPLOAD_SERVER" == "stuff@stuff.joyent.us" ]]; then
    echo "Uploaded to <https://stuff.joyent.us/stuff/$UPLOAD_BASE_LOCALDIR/$upload_subdir/>."
fi

